export const ADD_TO_DO='ADD_TO_DO';
export const EDIT_TO_DO='EDIT_TO_DO';
export const DELETE_TO_DO='DELETE_TO_DO';
export const LOAD_ALL_TODOS='LOAD_ALL_TODOS';
export const TOGGLE_TODO_STATUS='TOGGLE_TODO_STATUS';
export const ENABLE_TODO_EDITING='ENABLE_TODO_EDITING';
export const DISABLE_TODO_EDITING='DISABLE_TODO_EDITING';